### ISSUE TITLE
[Unit2] params not defined

### ISSUE THREAD

**Issue by angel-miguelez** [ennanco/MIA_ML1#3]
When executing

`Flux.train!(loss, params(ann), [(inputs', targets')], ADAM(learningRate))`

the following error occurs:

`UndefVarError: params not defined`

It can be solved by just importing `params` from the Flux library: 

`using Flux: params`

but this command is not provided in the notebook, so I think it would be better to update it.

**Comment by ennanco** [comment]
Yes, it is true that we have mislead the library in this case, however instead of importing permantly the function as you do, it is better to called it through the Library in a single line. It is better, in this case, due to the single use that we will be doing.
In any case, it is already modified. Thank you again for the feedback
